### ISSUE TITLE
No Tutorial on how to remove relationship on many_to_many_attributed.

### ISSUE THREAD

**Issue by hopecee** [datanucleus/samples-jdo#1]
Thanks for your Tutorial on ``many_to_many_attributed``. You demonstrated on how to add relation to an object but omitted how to remove it.

    // Establish the relation customer1 uses supplier2
    BusinessRelation rel1 = new BusinessRelation(cust1, supp2, "Friendly", "Hilton Hotel, London");
    cust1.addRelation(rel1);
    supp2.addRelation(rel1);

To remove relation from object, I did the following but the relationship object got deleted.

    tx.begin();
    ...
    BusinessRelation rel = pm.getObjectById(rel.getId());
    cust1.removeRelation(rel);
    supp2.removeRelation(rel);
    tx.commit();

Is relation deleted if it is not added to any object?

**Comment by andyjefferson** [comment]
So contribute one ...

**Comment by hopecee** [comment]
Done [here](https://github.com/datanucleus/samples-jdo/pull/2)
